Repository HotCake-Tanghuru/HotCake-BE, pull requests merged in 2023-12, with the labels that each got.

#19 ✨Feat: trend missions 상세 조회
  trend_missions/serializers.py
  trend_missions/tests.py
  trend_missions/urls.py
  trend_missions/views.py
Labels: enhancement

#24 ✨ Feature: 스탬프 발급
  trend_missions/models.py
  trend_missions/serializers.py
  trend_missions/tests.py
  trend_missions/urls.py
  trend_missions/views.py
Labels: enhancement

#21 ✨ Feature: 트렌드 미션 내용 수정 API
  trend_missions/models.py
  trend_missions/serializers.py
  trend_missions/tests.py
  trend_missions/urls.py
  trend_missions/views.py
Labels: enhancement

#26 ♻️ serializers 코드 수정
  trend_missions/serializers.py
Labels: documentation

#30 ✨ Feat: 카카오 로그인 및 회원가입
  accounts/models.py
  accounts/serializers.py
  accounts/tests.py
  accounts/urls.py
  accounts/views.py
  hotcake/settings.py
  hotcake/urls.py
  requirements.txt
Labels: enhancement

#33 ✨ Feature: 스탬프 상세 조회API
  trend_missions/tests.py
  trend_missions/urls.py
  trend_missions/views.py
Labels: enhancement

#36 🐛 Bug: Admin 계정 생성 에러 해결
  accounts/models.py
  hotcake/settings.py
Labels: bug

#38 ✨Feature: 트렌드 미션 좋아요 기능 구현
  accounts/models.py
  accounts/serializers.py
  hotcake/settings.py
  hotcake/urls.py
  trend_missions/tests.py
  trend_missions/urls.py
  trend_missions/views.py
Labels: enhancement

#39 ✨ Feature: 트렌드 미션 페이지 댓글&대댓글 API
  trend_missions/models.py
  trend_missions/serializers.py
  trend_missions/tests.py
  trend_missions/urls.py
  trend_missions/views.py
Labels: enhancement

#45 ✨ Feature: 트렌드 미션 페이지 상세 조회
  trend_missions/serializers.py
  trend_missions/tests.py
  trend_missions/urls.py
  trend_missions/views.py
Labels: enhancement

#46 :sparkles: Feat: 카카오 연결끊기와 함께 회원탈퇴
  accounts/urls.py
  accounts/views.py
Labels: enhancement

#47 ✨ Feat: 핫트렌드 API 구현
  hotcake/urls.py
  trends/serializers.py
  trends/urls.py
  trends/views.py
Labels: enhancement

#49 ♻️ Refactor: Swagger 적용 및 트렌드 미션 코드 수정
  hotcake/settings.py
  hotcake/urls.py
  requirements.txt
  trend_missions/models.py
  trend_missions/serializers.py
  trend_missions/tests.py
  trend_missions/urls.py
  trend_missions/views.py
Labels: bug, feat

#55 Feature: 사용자 프로필 조회 및 수정
  accounts/models.py
  accounts/permissions.py
  accounts/serializers.py
  accounts/tests.py
  accounts/urls.py
  accounts/views.py
  hotcake/settings.py
  hotcake/urls.py
Labels: enhancement

#57 ✨Feat: 팔로우 API
  accounts/serializers.py
  accounts/tests.py
  accounts/urls.py
  accounts/views.py
Labels: enhancement

#61 ✨ Feat: 유저 검색 API
  accounts/tests.py
  accounts/urls.py
  accounts/views.py
  trend_missions/views.py
Labels: enhancement

#66 ♻️ Refactor: 트렌드 앱 swagger 적용 및 트렌드 목록 조회 코드 수정
  trends/views.py
Labels: enhancement

#68 🗃️ 데이터베이스 연동
  hotcake/settings.py
  requirements.txt
  trend_missions/tests.py
Labels: documentation

#82 ♻️ Refactor: 접속중인 사용자 정보 표시
  accounts/urls.py
  accounts/views.py
Labels: enhancement

#85 🐛 Fix: cors에러 해결
  hotcake/settings.py
Labels: bug

#93 ♻️ Refactor: 카카오 로그인 api 분리
  accounts/urls.py
  accounts/views.py
Labels: bug

#99 ♻️ Refactor: 사용자의 트렌드 미션 조회 수정
  trend_missions/views.py
Labels: bug

#101 ♻️ Refactor: 트렌드 미션 생성 수정
  trend_missions/views.py
Labels: bug

#105 ♻️ Refactor: 트렌드 미션 상세 조회 수정
  trend_missions/views.py
Labels: bug

#107 ♻️ Refactor: 트렌드 미션 상세조회 수정
  trend_missions/views.py
Labels: bug

#108 ♻️ Refactor: 트렌드 미션 상세조회 수정 후 배포
  trend_missions/views.py
Labels: bug

#117 ♻️ Refactor: 트렌드 미션 상세 조회 댓글 수정
  trend_missions/serializers.py
  trend_missions/views.py
Labels: bug

#119 ✨ feat: 랜던한 트렌드 미션 데이터 조회 API 및 사용자 검색 수정
  accounts/views.py
  trend_missions/urls.py
  trend_missions/views.py
Labels: bug, enhancement
